iterative/dvc-bench

- .pre-commit-config.yaml
- setup.cfg
> pre-commit: initial

- .github/workflows/main.yml
- .gitignore
- asv.conf.json
- benchmarks/base.py
- convert_tags.dvc
- run_benchmarks.dvc
- setup_asv.dvc
> actions: run on mac and win

- benchmarks/startup.py
> base: add startup time benchmark

- benchmarks/base.py
> base: analytics fix

- benchmarks/status.py
20 ignore rules with 10k files tracked
3 ignore rules with 10k files tracked
Empty ignore rules file with 10k files tracked
> benchmark for dvc status with different numbers of ignore rules

- README.md
Instructions on how to run benchmarks on local copy of DVC.
> readme: instructions on testing local changes

- tests/test_machine_info.py
- write_asv_machine.py
Write platform into machine name, extend checksum numbers contained in machine name.
> machine: write platform name to machine name

- .github/workflows/regression_check.yml
Fixes #8 
Sample issue created by bot:
https://github.com/iterative/dvc-bench/issues/88
> regressions: read from rss and create issue

- benchmarks/startup.py
make benchmark run 50 times, per process.
> startup: fix benchmark params

- .github/workflows/regression_check.yml
- parse_feed.py
- requirements.txt
- setup.cfg
sample report #147 
FIxes #115
> regression check: new version

- .github/workflows/main_build.yml
- .github/workflows/nightly_build.yml
- .github/workflows/pull_request_build.yml
> benchmarks: disable analytics and updater

- .github/workflows/main_build.yml
- .github/workflows/nightly_build.yml
- requirements.txt
Related to #111 
Related to #131 
After using newer version of `asv` we should be getting more accurate windows machines descriptions.
> asv: install from repo

- asv.conf.json
> asv: configure regression thresholds

- .github/workflows/nightly_build.yml
> nightly build: show stderr

- .github/workflows/main_build.yml
- .github/workflows/nightly_build.yml
> main/nightly build: pull data for add benchmarks

- asv.conf.json
Clicking at the benchmark datapoint will redirect us to a particular commit.
> asv: config: add commit url

- asv.conf.json
- benchmarks/base.py
- benchmarks/checkout.py
- benchmarks/collect.py
- benchmarks/push.py
- benchmarks/status.py
- setup.cfg
> benchmarks: checkout, collect and push

- .github/workflows/main_build.yml
- .github/workflows/nightly_build.yml
- .github/workflows/pull_request_build.yml
> builds: turn off windows and darwin builds

- README.md
Inform user how to obtain `cats_dogs` data.
> readme: update running info

- benchmarks/collect.py
> benchmark: collect: increase number

- .dvc/config
- .github/workflows/pull_request_build.yml
- README.md
> repo: change default repo to public s3

- benchmarks/base.py
- benchmarks/imports.py
> Add a benchmark for imports

- benchmarks/base.py
- benchmarks/collect.py
> repo: benchmark brancher

- .github/workflows/pull_request_build.yml
> gh: cache dvc pull stage for future runs

- benchmarks/base.py
- benchmarks/update.py
> update: dont wrap the raw url

- .github/workflows/main_build.yml
- .github/workflows/nightly_build.yml
> builds: stop cleaning /tmp

- tests/benchmarks/cli/commands/test_init.py
> benchmark: cli: init: increase number of rounds

- tests/benchmarks/cli/commands/test_init.py
> benchmark: init: refactor

- action.yml
> action: use median for regression detection

- action.yml
Like we do on recent version:
https://github.com/iterative/dvc-bench/blob/77c71aa7960f64cc830d097ddc798045c545bea7/action.yml#L42
See also: #330
> Add fetch-depth=0 to sha from PR

- .github/workflows/build.yml
This reverts commit b0d88f724712982ef80c14f7e1a97a61e16a9eef.
> Revert "temporarily reduce dataset size (#328)"

- .github/workflows/build.yml
- scripts/ci/list_tests.sh
Reverts iterative/dvc-bench#337
> Revert "improve naming of jobs/report"

- tests/benchmarks/cli/commands/test_status.py
Benchmark for https://github.com/iterative/dvc/issues/7390
> status: add noop test

- tests/benchmarks/cli/commands/test_status.py
> status: modify the dataset

- .github/workflows/build.yml
- scripts/ci/list_tests.sh
reverts to `--group-by name` when comparing
Addendum to #337, fixes issues reported in https://github.com/iterative/dvc-bench/pull/337#issuecomment-1085956117
> improve naming

- tests/benchmarks/cli/commands/test_ls.py
Related to https://github.com/iterative/dvc/pull/7659
> bench: add test_ls

- tests/benchmarks/conftest.py
> bench: install older fsspec for 2.18.1, 2.11.0, 2.6.3

- data/chest-xray-pneumonia/.gitignore
- data/chest-xray-pneumonia/dataset.dvc
Similar to mnist/cats-dogs, but has larger image size (~300KB).
> data: add chest-xray-pneumonia

- data/meta-kaggle/.gitignore
- data/meta-kaggle/dataset.dvc
A dataset with big csv files. Useful to have around and is unlike what we currently have.
> data: add meta-kaggle

- data/.gitignore
- data/cats_dogs/.gitignore
- data/cats_dogs/dataset.dvc
To comply with the convention.
> data: move cats_dogs into a separate dir

- .github/workflows/build.yml
E.g. https://bench.dvc.org/run_id/123456/index.html
> gha: post workflow_dispatch results to gh-pages

- pyproject.toml
- requirements.txt
Reverts iterative/dvc-bench#514
> Revert "pin pytest"
