pyproject.toml

current `setup.cfg` does not force black to apply 79 columns limit. Fix in this PR.

black: add pyproject.toml

---

.github/workflows/main.yml

Fixes: #39 
Prerequisite for #38 
- new action named publish
- it waits for the build to finish, downloads results for all systems and joins them into single directory
- deploy joined results to our gh-page

GHA: join results before publishing

---

.github/workflows/main.yml
.github/workflows/pull_request_build.yml
benchmarks/base.py

Fixes #63 
It would be great to have reusable Github actions, though it seems its [not there yet](https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/10) for now we have to repeat some steps per each workflow.

dvc: turn off analytics

---

benchmarks/status.py

Fixes #78 
Increased timeout to 5 minutes. Windows is sooo slow.

DVCStatusBench: increase timeout

---

benchmarks/status.py

Related to #78 
[Test run](https://github.com/iterative/dvc-bench/actions/runs/140649664) seems to show that issue is fixed, lets wait for nightly build.

DVCIgnoreBench: increase timeout

---

run_benchmarks.dvc

So far our benchmarks are pretty basic, and they should be able to run on every version of dvc, so we should rerun existing and failed runs

asv: skip only succesfull runs

---

.github/workflows/main_build.yml
.github/workflows/nightly_build.yml

Before this change we could override windows and darwin new build results with old ones contained in dvc remote. The reason for that was order of merging the results - ubuntu got copied in the end, and since we do `dvc pull` during workflow execution, we obtain also windows and darwin results, which later override new results for those systems.

results: copy by system name

---

benchmarks/base.py
benchmarks/startup.py
benchmarks/status.py

#111 seems suspicious, we probably are not running enough benchmarks and are influenced by some unrelated things. This PR is first step to verifying that. We still need to rerun the commits in question (a11 - b5)

startup: increase bench runs

---

benchmarks/base.py

The number of processes means how many benchmark instances have to be run, so it is better to keep that number constant, in order to obtain results with same number of runs, independent of machine we are running on. Make repeat single number to not obfuscate how many times we actually run the benchmarks. It's hard enough as it is.

benchmark: fix default number of processes and repeat

---

.dvc/config
.github/workflows/pull_request_build.yml

PR builds for `Add` benchmarks has been failing due to lack of data.

GH actions: public data for PR build

---

.github/workflows/main_build.yml
.github/workflows/nightly_build.yml
.github/workflows/pull_request_build.yml
dvc.yaml
requirements.txt
tags_to_sha.py

Fixes #76 
I was wrong in #76. The problem was that asv did not cloned the repository. The fix for that is to run `asv check` before accessing cloned `dvc` repo.

pipeline: fix repo handling

---

parse_feed.py

Fixes #191 
Fixes #183 
We used to base our regressions detections on `updated` date, which was the date of the run, not the regression introduction. Now we will base that check on the date of the commit that "introduced" the regression. (Let's not forget that we do not benchmark all commits, hence "")

feed parsing: get regressions by last commit date

---

.github/workflows/regression_check.yml

Regression check stopped working after #192, because regression check workflow did not clone `dvc` repo before parsing the feed.

regression check: clone dvc before parsing commits

---

.github/workflows/main_build.yml
.github/workflows/nightly_build.yml
.github/workflows/pull_request_build.yml
requirements.txt
runner/.gitignore
runner/README.md
runner/main.tf
runner/setup_github_actions_runner.sh
runner/variables.tf

Fixes #203 
In this change, we create a terraform script that will be responsible for managing our own github actions runner.
That way we will have a constant execution environment, also, we should be more timeout-proof (github actions timeout for self-hosted runner is 72hrs (versus current 6hrs)).
I noticed that `/tmp` sometimes does not get cleaned up, so for now I introduced workaround cleaning it after each build. Need to investigate, as I am unable to reproduce on my own computer. Will create issue for that after this change gets accepted.

github actions: self hosted runner terraform script

---

benchmarks/base.py
benchmarks/push.py

Workaround for #207 
Since we are using only 1 process, we can cleanup `/tmp` before running `_setup`.
This is not a solution to #207.
I just need to get my hands on log, which is impossible if the step isn't [finished](https://github.com/iterative/dvc-bench/runs/1030350353?check_suite_focus=true)

Cleanup /tmp on setup

---

benchmarks/imports.py

Looks like https://github.com/iterative/dvc/issues/4485 improved performance by >10  times. So, in recent master, it seems it finished in ~10m.
So, 10 * 10 * 60 = 6000. 
I'll reduce it after checking the logs after this gets built.

Increase imports timeout

---

.github/workflows/main_build.yml
.github/workflows/nightly_build.yml
.github/workflows/pull_request_build.yml
.github/workflows/regression_check.yml

Seems like I was wrong to think that warnings popping up during build refer to our use of env:
https://github.community/t/environmental-files-on-windows/137631

github actions workflows: roll back migration to environmental files

---

.github/workflows/pull_request_build.yml

Now, instead of caching the `data/cats_dogs` it caches the `.dvc/cache`. Also in the later step it only fetches and for both cases, it uses `dvc checkout`.

gh: use checkout to get the downloaded data

---

benchmarks/add.py
benchmarks/base.py
benchmarks/imports.py
benchmarks/update.py

I couldn't find a name for a slightly bigger `mini` dataset, so I renamed it to 100x1024 and used 200x1024 for the bigger one.

benchs: add update benchmarks (for regular/to-remote import-url)

---

benchmarks/base.py
benchmarks/status.py

Resolves #262. Now every `file_1` will have the same content, so if you initially create a `medium` sized data dir and then create a `large` one DVC will able to tell you that the 5000 files already exist on the remote and 5000 files are new in your local environment instead of claiming every one of those are changed.

bench: stabilize contents for the same files

---

.gitignore
requirements.txt

Fixes #255 
I though migration to 2.0 will be harder. We do not rely on our dvc.lock when pulling (the only thing that we need to pull is data that has its own dvc files). `dvc.lock` was a problem when we were creating automated pull requests. But we do not do that  since #168. So we can just stop ignoring dvc.lock. Also, taking a look at #168 we can consider getting back to it - the reason for not using dvc back then was lack of builds per machine, which (might) be solved by parametrized stages.

bench: use dvc 2.0

---

.github/workflows/pull_request_build.yml
asv.conf.json

On wrong argument call fixed.
As to asv installation script, we include s3fs with `all` (in dvc) so no need to keep it there.

asv build fixes

---

.github/workflows/main_build.yml
.github/workflows/nightly_build.yml
.github/workflows/pull_request_build.yml

For download data step, we start using action that is supposed to retry the step if failed. It  seems that our builds fail quite often due to 500/503/522 errors on our aws serving public dataset.

builds: retry build if failed

---

benchmarks/add.py
benchmarks/base.py
benchmarks/gc.py
benchmarks/imports.py
benchmarks/pull.py
benchmarks/push.py
benchmarks/status.py
benchmarks/update.py

While browsing the benchmark logs I noticed that the add to cache benchmarks ran multiple times, which is something that we don't do for other remotes (because they tend to take a lot of time). So I've added `repeat=1` and `timeout=12000` to the `BaseRemoteBench`. If needed the subclasses can override those limits but I think they are fine as defaults.

benchs: repeat=1 for all remote benchmarks

---

benchmarks/gc.py

A couple problems related gc benchmark:
- Normal gc benchmark doesn't initialize dvc/git.
- Cloud gc benchmark uses the raw dataset name without the `.dvc` prefix
this patch resolves those issues.

benchs: initialize dvc/git for gc

---

requirements.txt

Seems like after extracting scmrepo the builds on the DVC side started to [fail](https://github.com/iterative/dvc/runs/4394751198?check_suite_focus=true).
Updating DVC should fix it, for now, though it seems to me that long-term solution should be to enable dependabot.

requirements: update DVC to 2.8.3

---

tests/conftest.py

Related to https://github.com/iterative/dvc/pull/7424 
This will make it possible for the bench pull request action to work again in the `dvc` repo

remove unused pools fixture

---

.github/workflows/build.yml

Reducing the dataset size should make it possible to run the benchmarks again while we wait for https://github.com/iterative/dvc/issues/7414 to fix #319

temporarily reduce dataset size

---

action.yml

We need to fetch all tags to help `setuptools_scm` deduce correct versioning.
So that we don't see `dvc-0.1.dev1+g81eee05` kind of version numbers in `benchmarks`.
See https://github.com/iterative/dvc/runs/5690662659?check_suite_focus=true#step:4:1773.

action: use fetch-depth=0 to fetch tags

---

run.sh

Fetch tags so that the version shows up correctly in `dvc version` and during `pip install`.

fetch tags

---

.github/workflows/build.yml
tests/benchmarks/conftest.py

We currently modify `name`, but not `fullname`, which results in generated `csv` not having correct name column.

bench: don't forget to modify fullname

---

scripts/ci/list_tests.sh
tests/benchmarks/cli/commands/test_data_status.py

These flags are the ones that are going to be used in VSCode extension, and is important for us to track. The previous one was a shallow status, which is faster compared to granular diff.

data status: bench with all flags including json

---

.pre-commit-config.yaml

CI lint step was broken because of updated flake8 URL:
https://github.com/PyCQA/flake8/issues/1737

fix flake8 URL

---

tests/benchmarks/cli/commands/test_checkout.py
tests/benchmarks/cli/stories/use-cases/test_sharing.py

`dvc.odb` was renamed to `dvc.cache` in https://github.com/iterative/dvc/pull/8987
Fixes CI https://github.com/iterative/dvc-bench/actions/runs/4169046364/jobs/7216558892

bench: don't use dvc.odb.local.path

---

.github/workflows/build.yml
scripts/ci/gen_html.sh

- drops deprecated GHA `set-output` usage
- uses `cml comment` for PR comment generation 
- also fixes issue where PR comments only had the last-run benchmark results instead of the full concat'd results

ci: use CML instead of create-pr-comment

---

.github/workflows/build.yml
requirements.txt

Adds S3 (`dvc_s3.tests.benchmarks` to the `dvc-bench` CI test suite). Daily builds are run against real S3, otherwise moto will be used

ci: add S3 to dvc-bench benchmarks

---

.github/workflows/build.yml

We may also need to just reduce the # of revs we test for S3, aws token timeout is currently 4 hours, not sure it is worth extending it

ci: set s3 timeout to 4 hrs

---

.github/workflows/build.yml

Allows bench.dvc.org to still be updated as long as the main benchmarks run successfully (so s3/azure/gcs timeouts do not prevent the overall build)

ci: allow failures in real remote tests

---

requirements.txt

Should fix deploy/publish CI: https://github.com/iterative/dvc-bench/actions/runs/6937330780/job/18875133391
pytest-benchmark[histogram] depends on pygal, recent pygal changes now use `importlib_metadata` but the dependency is missing from the pygal install requirements
see: https://github.com/Kozea/pygal/issues/545

requirements: add explicit pygal dependencies

---

.github/workflows/build.yml
requirements.txt

- removes pinned pre-commit from requirements.txt and build workflow in favor of using pre-commit.ci (latest pinned pre-commit now causes pip conflicts due to incompatible platformdirs ranges between `dvc` and `virtualenv`)

ci: use pre-commit.ci

---

pyproject.toml
requirements.txt

Newer release of `pytest` 8.1.0 is breaking `flaky` plugin. Pinning the pytest version temporarily.
```pytb
Run echo "tests=$(./scripts/ci/list_tests.sh)" >> $GITHUB_OUTPUT
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.13/x64/bin/pytest", line 8, in <module>
sys.exit(console_main())
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/config/__init__.py", line 195, in console_main
code = main()
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/config/__init__.py", line 153, in main
config = _prepareconfig(args, plugins)
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/config/__init__.py", line 335, in _prepareconfig
config = pluginmanager.hook.pytest_cmdline_parse( …
```

pin pytest

---

.github/workflows/build.yml

See https://github.com/iterative/dvc-bench/actions/runs/10840696905/job/30083510194
I've replaced the ClickOops hot mess we had with my Terraform recipe under a new Google Cloud provider; now it works as intended.
Also, switched to use `environment`-based subject conditions for extra security.

Fix OpenID Connect for Google Cloud
